//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linqCockroach {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class DefSet : global::System.Configuration.ApplicationSettingsBase {
		
		private static DefSet defaultInstance = ((DefSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefSet())));
		
		public static DefSet Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("linqCockroach")]
		public string AppName {
			get {
				return ((string)(this["AppName"]));
			}
			set {
				this["AppName"] = value;
			}
		}
	}
}
